name: Release
on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Whether to run the release in non-destructive dry-run mode.
        type: boolean
        required: false
        default: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [16.x]

    steps:
      - name: ğŸ“š Checkout
        uses: actions/checkout@v2

      - name: âš™ï¸ Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ’¾ Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles( '**/yarn.lock' )}}
          restore-keys: ${{ runner.os }}-node-

      - name: ğŸ“¦ Install Dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: ğŸ—ï¸ Build
        run: yarn build

      - name: ğŸ“„ Prepare .npmrc File
        run: |
          NPM_TOKEN=${{ secrets.NPM_TOKEN }}
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc

      - name: ğŸš€ Release (Dry Run)
        if: ${{ inputs.dry-run }}
        run: yarn test-release

      - name: ğŸš€ Release
        if: ${{ !inputs.dry-run }}
        run: yarn release