name: Tests
on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - name: ğŸ“š Checkout
        uses: actions/checkout@v2

      - name: âš™ï¸ Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ’¾ Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles( '**/yarn.lock' )}}
          restore-keys: ${{ runner.os }}-node-

      - name: ğŸ“¦ Install Dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: ğŸ“„ Prepare .env files
        run: |
          echo "DISCORD_LOGGING_BOT_CHANNEL=${{ secrets.DISCORD_LOGGING_BOT_CHANNEL }}" >> .env.bot
          echo "DISCORD_LOGGING_BOT_TOKEN=${{ secrets.DISCORD_LOGGING_BOT_TOKEN }}" >> .env.bot
          echo "DISCORD_LOGGING_WEBHOOK_URL=${{ secrets.DISCORD_LOGGING_WEBHOOK_URL }}" >> .env.webhook

      - name: ğŸ§ª Test
        run: yarn test